import { AnonymousCredentialPolicy } from "@azure/storage-blob";
import { RandomNumberGenerator } from "@microsoft/sp-core-library";

export interface IReportingPortalState {
  ReportCategories: any[];
  ReportCategory: any;
  ReportTypes: any[];
  ReportType: any;
  ReportIndexes: any[];
  CurrentReportIndex: any;
  ReportData: any[];
  FilteredReportData: any[];
  columns: any[];
  IndexValue: string;
  IndexQuery: string;
  ParsedIndexQuery: string;
  ConditionCount: number;
  ShowBubble: boolean;
  BubbleTarget: string;
  BubbleMessage: string;
  Condition: string;
  manageReportViewModal: boolean;
  CurrentReportEmbedURL: string;
  UserPermissions: any[];
  UserRoles: any[];
  Countries: any[];
  Regions: any[];
  Areas: any[];
  Branches: any[];
  Departments: any[];
  ReportLevels: any[];
  SelectedCountry: any;
  SelectedReportLevel: any;
  SelectedReportLevelValue: any;
  ReportLevelValues: any[];
  IsDataLoading: boolean;
  IsAccessAvailable: boolean;
  IsReportLoading: boolean;
  SelectedReports: any[];
  confirmReportDownloadModal: boolean;
  IsDownloadAll: boolean;
  manageHelpDocumentViewModal: boolean;
  manageLoadingModal: boolean;
  ScreenLoadingMsg: string;
  IsConnectionFailed: boolean;
  ShowParentOnly: boolean;
  CurrentReportFile: any;
  CurrentHelpDocumentBlob: any;
  managMessageModal: boolean;
  indexDateValue: boolean;
  startDateValue: any;
  endDateValue: any;
  indexNameValue: boolean;
  ReportLevelIndexName: any[];
  SelectedReportLevelIndexName: any;
  value: string;
  indexValues: any[];
  fetchedindexValuesArray: any[];
  lastSearchIndexName: string;
  indexQueryArray: any[];
  allowAddIndex: boolean;
  addedCondition: string;
  NoOfIndexValueChar: number;
  indexQueryDateFormat: string;
  parseQueryDateFormat: string;
  ReportIndexValues: any[];
  previousSelectedDept: any[];
  selectedDept: any[];
  previousSelectedIndexValue: any;
  isDeptChanged: boolean;
  invoiceSTDColumns: any[];
  invoiceCONColumns: any[];
  HCMColumns: any[];
  GLReportColumns: any[];
  reportsPermission: string;
  networkID: string;
  Sensitive: string;
  Selector: any[];
  searchInput: any;
  isGetInvoiceFetchRecord: boolean;
  totalCountDisplayMsg:string;
  totalRecordCount:string;
  totalRecordCountNumber:number;
  invoiceNumberLimitation:number;
  isAllRowSelect:boolean;
  isItemSelect:boolean;
  ReportTypesValues: any[];
  downloadFilesCount:number;
  downloadBatchSize:number;
}
